version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:16
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # run build/test/lint
      - run: yarn prepack
      - run: yarn lint
      - run: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  publish:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Set release version
          command: yarn version $CIRCLE_TAG
      - run:
          name: Authenticate with registry
          command: yarn config set 'npmRegistries["//registry.npmjs.org/"].npmAuthToken' "$NPM_TOKEN"
      - run:
          name: Publish package
          command: yarn npm publish
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          context: beryl-basis-global
          filters:
            tags:
              only: /.*/
      - publish:
          context: beryl-basis-global
          requires:
            - build
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
